### PR TITLE
FIX: normalize whitespace; fix eslint errors

### PR DESCRIPTION
**Pull request by selrond**

### CODE REVIEW

**Comment by ahmadawais** [comment]
@selrond thanks for the PR but without a description and details on how you tested the PR and some screenshots or things like that, I am never able to merge a PR. Care to update that?

**Comment by selrond** [comment]
@ahmadawais I've done that on purpose, as "fixing whitespace" really does nothing to the code. It takes literally 2 seconds to click into "Files changed" tab right above, while it would take multiple times more to provide "screenshots". I can't even think what I'd screenshot  - the diff itself?

**Comment by selrond** [comment]
@ahmadawais I understand your intention, but it's really pointless in that case

**Comment by selrond** [comment]
@ahmadawais also worth noting - "providing a description of how you tested the PR" is nearly identical to not test it at all - there should be automated tests in place, really

**Comment by selrond** [comment]
@ahmadawais so you're still waiting for the screenshots?

**Comment by ahmadawais** [comment]
@selrond 
>I've done that on purpose, as "fixing whitespace" really does nothing to the code. It takes literally 2 seconds to click into "Files changed" tab right above, while it would take multiple times more to provide "screenshots". I can't even think what I'd screenshot - the diff itself?

I don't appreciate the tone here. We have a procedure in place for a reason. 

> there should be automated tests in place

How about you take time and create automated tests for the repo? It's a Free and Open Source Project after all.

>so you're still waiting for the screenshots?

I don't accept PR's without description and details that I asked for.

**Comment by selrond** [comment]
@ahmadawais 
Look. It's 12 lines of code, GitHub even highlights the changes for you... 

I do understand the necessity of having a process in place, but in this case, requiring "screenshots" and "descriptions of how I tested it" is ridiculous.

> I don't appreciate the tone here. We have a procedure in place for a reason.

I still don't understand how is this a procedure, when in fact it does not guarantee _anything_ (does it?). 

> How about you take time and create automated tests for the repo? It's a Free and Open Source Project after all.

I pointed out an improvement that could be made, I did _not_ attack you for not having it already.

I totally understand you not having time to set up automatic testing or whatever, but - seriously - is it really that hard to make one small step from your side as well instead of forcing your process regardless of the circumstances?

The whole point of mine is to be __sensible__ about it.

To be honest, I wanted to contribute more to this project (as I like it, and it helped me in a project), but the way you communicate (_"that's the way it is, that's the way it should be, put up with it or get off"_) really puts me off.

**Comment by ahmadawais** [comment]
I'm closing this PR as the author is not interested in following a simple procedure in place. Also, the tone of this whole thread is offensive.

**Comment by selrond** [comment]
Exactly what I was talking about...

**Pull request closed without merging**
