### PR TITLE
 IMPROVE: Remove anonymous function for better Gulp console output

### PR DESCRIPTION
**Pull request by JeremyEnglert**
## Description 
There was an anonymous function in the default task, which led to an awkward and non-helpful output (`Starting anonymous`) when starting Gulp. This was fixed by naming the function `watchFiles`.

## Screenshots: 
screen shot 2018-01-15 at 12 57 52 am

## Types of changes
Gave anonymous function a name.

## How Has This Been Tested?
Ran default task. Works as expected.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has extensive inline documentation like the rest of WPGulp.

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
I need to stop making PR's at 2am hahha. Fixed!

**Comment by ahmadawais** [comment]
HAHA! No worries.

**Comment by ahmadawais** [comment]
@JeremyEnglert Why do we need to name that function? Any specific reason?

**Comment by JeremyEnglert** [comment]
See attached. Since the function does not have a name, it shows as "anonymous" function in the Gulp output - which isn't very useful. Also, as we add error handling, it will make it easier to see which task/function caused the error if they all have names.

screen shot 2018-01-15 at 11 51 00 am

**Comment by ahmadawais** [comment]
I'm convinced.

**Pull request merged**
