### PR TITLE
🚀 FIX: gulp dependencies in package.json

### PR DESCRIPTION
**Pull request by kevinhuddy**
## Description
Fixed issue #128 by replacing "gulp": "github:gulpjs/gulp#4.0" with "gulp": "^4.0.0" in package.json

## Screenshots:
screenshot 2018-10-23 12 58 33

## Types of changes
FIX

## How Has This Been Tested?
Tested by me locally on an active project.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has extensive inline documentation like the rest of WPGulp.

### CODE REVIEW

**Comment by parys-github** [comment]
Hi, guys, I am not really sure what is going on.
After the last update, wpgulp installing perfectly, 
my styles are compressed properly but unfortunately **vendor.js** and **custom.js** still stay **UnCompressed.** 
Do I need to create an extra task? 
Seems to be right now both tasks for Vendor and Custom contain: 
**pipe( uglify() )**
Any idea what is wrong?
Regards

**Comment by ahmadawais** [comment]
@parys-github kindly create a new issue and answer all the steps there are while you file a bug report.

**Comment by parys-github** [comment]
Thanks Ahmad, I will be very grateful for some advice on where to look for a solution.

**Comment by ahmadawais** [comment]
@parys-github sure but go here and file an issue https://github.com/ahmadawais/WPGulp/issues/new?template=Bug_report.md

**Pull request merged**
