### PR TITLE
FIX: Better async support

### PR DESCRIPTION
**Pull request by JeremyEnglert**
## Description 
The tasks were only returning `gulp`, which led to some async related errors. This PR makes all tasks return a stream, which is necessary for proper async usage.

https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#async-support

## Types of changes
No changes beyond fixing some async related errors.

## How Has This Been Tested?
Ran default Gulp tasks as well as specific tasks to ensure they still function as expected.

### CODE REVIEW

**Comment by ahmadawais** [comment]
It was my ESLint that would do this onSave. Does that matter? I suppose it would automatically pick up the stream?

**Comment by JeremyEnglert** [comment]
> It was my ESLint that would do this onSave. Does that matter? I suppose it would automatically pick up the stream?

It could. But this PR formats it the way the docs reccomend and also seems to be a "best practice" across other projects. Returning `gulp` on it's own may cause unexpected issues, as it is not a stream.

**Comment by ahmadawais** [comment]
@JeremyEnglert We'll need to fix ESLint for that. I happen to think that gulp is not being returned here, the stream is, can you prove otherwise? Coz this would break so many other projects and that's not what happens?

**Comment by ahmadawais** [comment]
@JeremyEnglert I'm going ahead and merging this one, but still looking forward to your response.

**Comment by JeremyEnglert** [comment]
@ahmadawais - it looks like your right, it was grabbing the stream. However, the formatting makes it looks like the task is only returning `gulp`. 

However, as this is a tool for many new Gulp users, I believe it makes sense to keep the formatting as close to the Gulp docs/best practices as possible. If this was confusing to us, I can only imagine the confusion for a user who is completely new to Gulp.

**Pull request merged**
