### PR TITLE
NEW: Gulp Deploy Command

### PR DESCRIPTION
**Pull request by musicaljoeker**
## Description

A bit of a large change set with this one, so I will describe things in detail.

My goal was to modify existing gulp tasks (styles, customJS, vendorJS, etc...) allowing them to deploy a production build to a distribution directory. 

To do this I needed to add two NPM package dependencies:
- [gulp-if](https://www.npmjs.com/package/gulp-if): This helped me determine if the current gulp task is deploying to the distribution directory, or if it is running tasks relative to the root directory.
- [gulp-clean](https://www.npmjs.com/package/gulp-clean): This allowed me to easily clean (or delete) the /dist directory each time the `gulp deploy` command was run.

I added a new helper boolean variable (`isDeploying`) that toggles on and off when you are deploying. Default is set to false. I'm not a huge fan of global variables, but I couldn't figure out a way to pass parameters into gulp tasks.

I added three new helper functions called cleanDeployment, toggleIsDeploying, and deployScreenshot. Those should be pretty self explanatory.

I added two new gulp tasks:
- `deployPHP`: This deploys all PHP files in the root directory to the deployment directory
- `deploy`: Cleans the deployment directory, toggles the isDeploying boolean, deploys code to the deployment directory, and toggles the isDeploying boolean again.

Additional notes: I don't include any non-minified or map files in the deployment build.

## Screenshots:
https://imgur.com/8nAIjcD

## Types of changes
NEW: adds a new `gulp deploy` command to make a deployment-ready build of your code. Since this is a fairly large change-set, I recommend testing this yourself a little bit. :) I'll gladly take any feedback you are willing to give. 👍

## How Has This Been Tested?
I've tested to ensure that the `npm start` command continues to work as expected, and from what I can tell, it does. I've tested my `gulp deploy` command multiple times to ensure that things clean and build as I expect. I've also tried taking what's in the /dist folder and deploying it to one of my dev environments with no problems.

## Checklist:
- [ x ] My code is tested.
- [ x ] My code follows the WordPress code style. (To the best of my knowledge)
- [ x ] My code follows has extensive inline documentation like the rest of WPGulp.

### CODE REVIEW

**Comment by alassetter** [comment]
Nice work. I had been working on this problem myself. Your solution was much more elegant. So thank you.

**Style.css Not Minified on Deployment**
Don't you want the style.css to be minified on deployment? If so you would need to change line 170 to isDeploying versus ! isDeploying
Right?

My last piece to this puzzle was adding Gulp Zip. Thought this may help someone.

`// Set the Theme name to be used in zipping up the production theme
const themeName = 'themename';`

`/**
 * ZIP Tasks.
 * Task: `zip`.
 *
 * 1. Zip the production files up for deployment
 * 2. Rename the folder to your Theme Name set at the beginning of the gulp file. 
 */
gulp.task('zip', () => {
	return gulp
    	.src( config.DeployDestination + themeName + "/**" )
        .pipe(zip( themeName + ".zip" ))
        .pipe(gulp.dest( config.styleDeployDestination ))
	.pipe( notify({ sound: "Beep", message: '\n\n✅  ===> ZIP THEME — completed!\n', onLast: true }) );
});`

**Comment by musicaljoeker** [comment]
Hi @alassetter, you are correct that you want the stylesheet to be minified (and if you try running it, and check the contents, it does minify), however when you deploy your stylesheet, you don't want the name of the stylesheet to be `style.min.css`, you want it to be `style.css` so that WordPress picks up that resource. See [WordPress required files](https://developer.wordpress.org/themes/release/required-theme-files/).

Great idea on automatically zipping on `gulp deploy`. I've added that functionality to the task.

**Comment by musicaljoeker** [comment]
Is there anything that I can do to help move this pull request along, @alassetter or @ahmadawais? Is this still a needed feature? I'm happy to continue contributing to this project. 👍

**Comment by alassetter** [comment]
@musicaljoeker I think it is a great feature. But I believe @ahmadawais must approve it first.

**Comment by wowthemesnet** [comment]
Great feature! Tested and worked for me without any issues! Thank you, @musicaljoeker !

**Comment by ahmadawais** [comment]
Implemented a different version of this https://github.com/ahmadawais/WPGulp/issues/188#issuecomment-716127011

**Pull request closed without merging**
