### PR TITLE
IMPROVE added babel support of ESNext

### PR DESCRIPTION
**Pull request by saltnpixels**
Added babel to gulp and package.json files so WPGulp now supports ESNext

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
Hi @saltnpixels - it looks like we have some conflicts here. I'm guessing you made your changes to the master branch, so the changes recently pushed to the 2.0 branch did not make it into your PR. 

PS - Super stoked to see Babel support added!

**Comment by saltnpixels** [comment]
I'm going deeper down the rabbit hole. I got the 2.0 branch, made the changes but can't test it because I don't have gulp 4 installed...
sigh...

**Comment by ahmadawais** [comment]
@saltnpixels then install it? What's the catch here? Create a new dummy project and start WPGulp from scratch. Download the `package.json`, `config.js` and `gulpfile.js` in a theme or plugin folder and then run `npm install`

**Comment by saltnpixels** [comment]
How can i run gulp 4.0 not globally.
I dont want to install it globally.

Right now i get an error that gulp.parallel is not a function.

**Comment by JeremyEnglert** [comment]
Check out this article on running specific versions of Gulp: https://jondavidjohn.com/keeping-it-local-with-npm-scripts/

**Comment by ahmadawais** [comment]
Fixed in #80

**Pull request closed without merging**
