### PR TITLE
NEW: Add ES6 support to WPGulp using gulp-babel 💯

### PR DESCRIPTION
**Pull request by asharirfan**
Adds `gulp-babel` to WPGulp to support the conversion of ES6 JS to browser compatible JS.

## Screenshots:
alt text

## Types of changes
NEW: Add ES6 support to WPGulp using gulp-babel 💯

## How Has This Been Tested?
Test:
alt text

Result:
alt text

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has extensive inline documentation like the rest of WPGulp.

### CODE REVIEW

**Comment by JeremyEnglert** [comment]
This looks great at first glance!

I also believe Babel is something that will only need to run on changed files, correct? If so, I can modify the JS caching (https://github.com/ahmadawais/WPGulp/pull/79) to take that into account.

**Comment by asharirfan** [comment]
Yes @JeremyEnglert, I believe so. Since the changes are only made to the source file and in return, the result/output file is updated.

**Comment by JeremyEnglert** [comment]
This looks great! But there is now a conflict. I imagine this is going to happen a lot as we build 2.0, as most of the work is done in 1 or 2 files. 

@ahmadawais, any ideas on how to avoid this or make it smoother?

**Comment by ahmadawais** [comment]
@JeremyEnglert @asharirfan I am open for recommendation. As the project is growing, we cannot just keep contributing to one single branch. What needs to be done here is that we need to have separate feature branches with username prefixes E.g. `asharirfan/es6`, `ahmadawais/es6` and then we can have a parent `es6` branch optionally that could be later merged by me to the `v2.0.0` branch.

**Comment by JeremyEnglert** [comment]
> @JeremyEnglert @asharirfan I am open for recommendation. As the project is growing, we cannot just keep contributing to one single branch. What needs to be done here is that we need to have separate feature branches with username prefixes E.g. asharirfan/es6, ahmadawais/es6 and then we can have a parent es6 branch optionally that could be later merged by me to the v2.0.0 branch.

I think the username branches can be done on user's individual Git accounts. But I like the idea of feature branches. Although this still won't 100% solve the problem, as these feature branches will fall behind as other work is done. I think it's just one of those things we'll have to "deal with" as the bulk of the work is done in a few files. 

In a case like this, do we ask the submitter to fix the branch, or should one of the reviewers do so?

**Comment by ahmadawais** [comment]
@JeremyEnglert You're right. I guess this is unavoidable. And yes, both contributor or a reviewer can do it. Whoever finds time. I also think that we should set some sort of a release date and work towards it.

I am thinking that the release should be next month. Let's discuss it in a separate issue.

**Comment by JeremyEnglert** [comment]
Fixed conflicts. 

Also, I think this is something that should be added to the vendorsJS task. But that could be a separate PR.

@asharirfan, do you want to handle that?

@ahmadawais, this should be good to merge. But I'd appreciate you putting a second set of eyes on the fixes I made.

**Comment by asharirfan** [comment]
@JeremyEnglert, sure. I will take care of it. I will send a commit shortly.

**Comment by ahmadawais** [comment]
@JeremyEnglert @asharirfan it looks good to me, I am interested in hearing your thoughts about how this code is tested. 

@asharirfan have you tested this code with some vendor scripts to find out how the go through with the babel process? Also there's a lot of repetition in both the JS tasks. It would be worth the effort to create one config for both and then run it in both via a simple JS function but that should be done in a separate PR.

Just let me know about the tests you run with some custom and vendor (both ES6 and ES5 code libs). And I'll merge this one.

**Comment by JeremyEnglert** [comment]
> Also there's a lot of repetition in both the JS tasks. It would be worth the effort to create one config for both and then run it in both via a simple JS function but that should be done in a separate PR.

I think that sounds like a good idea. But I can also see why it's good to keep them as is. Some users may have different presets for vendorJS vs. customJS. But I'm not sure how often that would happen. So either way is fine by me.

**Comment by JeremyEnglert** [comment]
PS - This is a blocking PR for me, as it makes changes to package.json and gulpfile.js. So the sooner this can be merged, the better on my end. :)

I ran the following code:

```
jQuery(document).ready(function () {
	let x = "y";
});
```

Which was transpiled by Babel into:

```
jQuery(document).ready(function () {
	var x = "y";
});
```

I also ran Foundation 6 files through Babel and it compiled as expected. 

However, depending on which browsers we want to support, Babel may not be necessary anymore: https://medium.freecodecamp.org/you-might-not-need-to-transpile-your-javascript-4d5e0a438ca

**Comment by ahmadawais** [comment]
@JeremyEnglert So, what do you think? Does the vendor function working fine with Babel? If so then let's merge this.

**Comment by JeremyEnglert** [comment]
> @JeremyEnglert So, what do you think? Does the vendor function working fine with Babel? If so then let's merge this.

Yup! This works as expected for `vendorsJS` and `customJS`. It has my approval for merging.

**Comment by ahmadawais** [comment]
There you have it. Merged. I haven't tested it yet, but I'll take your word for it this time.

**Pull request merged**
