### PR TITLE
Styles reload

### PR DESCRIPTION
**Pull request by commwork**
I would add this because beginners maybe wonder why this is not working
from start.

### CODE REVIEW

**Comment by ahmadawais** [comment]
It will trigger a reload every time there is a change. Not everyone wants that. I don't! I let my styles get included in the form of an injected CSS. So, I will not be merging this PR. 

Thanks a lot for your interest in this project, I hope you contribute in the future as we grow.

**Comment by commwork** [comment]
Aaaaah, okay now I understand. Because of commentet "injectChanges: true" nothing happened on style change so me as a absolute beginner needed hours to figure out why changing my scss didn't reload the browser ;) - now i understand that "injectChanges"-thing.

**Comment by ahmadawais** [comment]
@commwork  Must always read the source code. Actually, I haven't blogged about the new features yet. I will do that sooner than later.

**Comment by commwork** [comment]
I am working on a new theme with this based on underscore and everything is working very fine :).

**Comment by ahmadawais** [comment]
@commwork I'll take that as a compliment :)

**Comment by ahmadawais** [comment]
Hey, I just committed an update and commented the media queries merge lines. These two lines were causing CSS to not reload 

```
// Uncommenting these two lines will help merging the media queries
		// but there is a known issue, SCSS changes stop reloading the browser
		// which is why for now I recommend you to only uncomment these two lines
		// to process the media queries.
		//.pipe(filter('**/*.css')) // Filtering stream to only css files
		//.pipe(mmq({ log: true })) // Merge Media Queries only for .min.css version.
```

**Comment by commwork** [comment]
Thanks for the update ;)

**Pull request closed without merging**
